language: cpp
before_script:
- sudo apt-get install cmake
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install libpthread-stubs0-dev
- sudo apt-get install libgtest-dev -y
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo mkdir -p /usr/local/lib/gtest
- sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
- sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
- cd -
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cd task_3/
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
          - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -utopp13:$BINTRAY_API_KEY "https://api.bintray.com/content/topp13/otus/allocator/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
